# Generated by Django 3.1 on 2021-06-19 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsDepense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_depense', models.CharField(choices=[('MATERIELS', 'Materiels'), ('FRAIS OUVRIER', 'Frais_Ouvrier'), ('LOCATION', 'Location'), ('ELECTRICITE', 'Electricite'), ('CONSOMMABLE', 'Consommable'), ('IMPOT SYNTHETIQUE', 'Impot_synthetique'), ('TAXE MUNICIPAL', 'Taxe_municipal')], default='Materiels', max_length=30)),
                ('type_materiel', models.CharField(choices=[('FIL', 'Fil'), ('AIGU', 'Aigu'), ('SATIN', 'Satin'), ('POPILINE', 'Popiline'), ('DUPURE', 'Dupure'), ('CISEAU', 'Ciseau'), ('CHARBON', 'Charbon'), ('COL', 'Col')], default='Fil', max_length=30)),
                ('quantite', models.PositiveSmallIntegerField(default=1)),
                ('prix_unitaire', models.PositiveIntegerField(blank=True, null=True)),
                ('montant_unitaire', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('status', models.CharField(choices=[('Client', 'CLIENT'), ('Ouvrier', 'OUVRIER'), ('Apprenti', 'APPRENTI'), ('Fournisseur', 'FOURNISSEUR'), ('Company', 'COMPANY')], default='CLIENT', max_length=20)),
                ('sex', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autres')], default='Homme', max_length=20)),
                ('prenom', models.CharField(blank=True, max_length=30, null=True)),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_1', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(choices=[('G', 'Grande'), ('M', 'Moyenne'), ('P', 'Petite')], default='Grande', max_length=20)),
                ('domicile', models.CharField(blank=True, default='Lafiabougou', max_length=30, null=True)),
                ('alias', models.CharField(blank=True, max_length=30, null=True, verbose_name='alias')),
                ('profession', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_2', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.DateField(auto_now_add=True)),
                ('nationalite', models.CharField(blank=True, max_length=30, null=True)),
                ('tutuelle', models.CharField(blank=True, max_length=30, null=True)),
                ('telephonique_fix', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_reference', models.PositiveIntegerField(blank=True, null=True)),
                ('nina', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(choices=[('Boubou', 'Boubou'), ('Grand Boubou', 'Grand Boubou'), ('Chemise Complet', 'Chemise Complet'), ('Chemise Manche Long', 'Chemise Manche Long'), ('Chemise Manche Court', 'Chemise Manche Court'), ('Pagne Jupe', 'Pagne Jupe'), ('Pagne Complet', 'Pagne Complet'), ('Pagne Maniere', 'Pagne Maniere'), ('Patanlon', 'Patanlon'), ('Tenu Scolaire', 'Tenu Scolaire'), ('Tenu Securite', 'Tenu Securite'), ('AUTRES', 'AUTRES')], default='Boubou', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.FloatField(blank=True, null=True)),
                ('rendez_vous', models.DateTimeField()),
                ('livre', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('command_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalaliso.person', verbose_name='Titulaire command')),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('mesure_modele', models.CharField(choices=[('Boubou', 'Boubou'), ('Grand Boubou', 'Grand Boubou'), ('Chemise Complet', 'Chemise Complet'), ('Chemise Manche Long', 'Chemise Manche Long'), ('Chemise Manche Court', 'Chemise Manche Court'), ('Pagne Jupe', 'Pagne Jupe'), ('Pagne Complet', 'Pagne Complet'), ('Pagne Maniere', 'Pagne Maniere'), ('Patanlon', 'Patanlon'), ('Tenu Scolaire', 'Tenu Scolaire'), ('Tenu Securite', 'Tenu Securite')], default='Boubou', max_length=50, primary_key=True, serialize=False)),
                ('coude', models.FloatField(blank=True, null=True)),
                ('epaule', models.FloatField(blank=True, null=True)),
                ('manche', models.FloatField(blank=True, null=True)),
                ('tour_manche', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('poitrine', models.FloatField(blank=True, null=True)),
                ('longueur_boubou', models.FloatField(blank=True, null=True)),
                ('longueur_patanlon', models.FloatField(blank=True, null=True)),
                ('fesse', models.FloatField(blank=True, null=True)),
                ('ceinture', models.FloatField(blank=True, null=True)),
                ('cuisse', models.FloatField(blank=True, null=True)),
                ('patte', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('mesure_client', models.ManyToManyField(to='kalaliso.Produit', verbose_name='Mesure Par Produit')),
                ('person_mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalaliso.person', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/modele/%Y/%m/%d', verbose_name='Photo_commande')),
                ('couture', models.CharField(choices=[('BRODERIE', 'Broderie'), ('COUTURE SIMPLE', 'Couture simple'), ('COUTURE A MAIN', 'Couture a main'), ('REPARATION', 'Reparation')], default='Broderie', max_length=25)),
                ('tissu', models.CharField(choices=[('BAZIN GETZNER', 'BAZIN GETZNER'), ('BAZIN RICHE', 'BAZIN RICHE'), ('BAZIN MOYEN', 'BAZIN MOYEN'), ('WAX', 'WAX'), ('TISSU', 'TISSU'), ('LEGER', 'LEGER'), ('BRODE', 'BRODE'), ('PERCALE', 'PERCALE'), ('VOILE', 'VOILE'), ('BOGOLAN', 'BOGOLAN'), ('AUTRES', 'AUTRES')], default='BAZIN GETZNER', max_length=25)),
                ('couloir', models.CharField(choices=[('BLANCHE', 'BLANCHE'), ('ROUGE SANG', 'ROUGE SANG'), ('BLEU', 'BLEU'), ('ORANGE', 'ORANGE'), ('ROSE', 'ROSE'), ('VERT', 'VERT'), ('GRIS', 'GRIS'), ('GRIS CLAIR', 'GRIS CLAIR'), ('VIOLET', 'VIOLET'), ('MARON', 'MARON'), ('MARON CLAIR', 'MARON CLAIR'), ('TURGUOISE', 'TURGUOISE'), ('JAUNE', 'JAUNE'), ('JAUNE COUSIN', 'JAUNE COUSIN'), ('NOIR', 'NOIR'), ('BAGA', 'BAGA'), ('BAGA CLAIR', 'BAGA CLAIR'), ('DEUX TONS', 'DEUX TONS'), ('MULTICOLOR', 'MULTICOLOR')], default='BLANCHE', max_length=25)),
                ('quantite', models.PositiveSmallIntegerField()),
                ('metrage', models.FloatField()),
                ('price', models.FloatField()),
                ('avance', models.FloatField()),
                ('reliquat', models.FloatField()),
                ('remise', models.FloatField(default=0)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kalaliso.orders')),
                ('products', models.ManyToManyField(to='kalaliso.Produit', verbose_name='list_commande')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.PositiveIntegerField(blank=True, null=True)),
                ('is_valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titulaire_depense', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kalaliso.person', verbose_name='Titulaire Depense')),
            ],
        ),
    ]
