# Generated by Django 3.1 on 2020-09-27 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Client', 'CLIENT'), ('Ouvrier', 'OUVRIER'), ('Apprenti', 'APPRENTI'), ('Fournisseur', 'FOURNISSEUR'), ('Company', 'COMPANY')], default='CLIENT', max_length=20)),
                ('sex', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autres')], default='Homme', max_length=20)),
                ('prenom', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('contact_1', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(choices=[('Boubou', 'Boubou'), ('Grand Boubou', 'Grand Boubou'), ('Chemise Complet', 'Chemise Complet'), ('Chemise Manche Long', 'Chemise Manche Long'), ('Chemise Manche Court', 'Chemise Manche Court'), ('Pagne Jupe', 'Pagne Jupe'), ('Pagne Complet', 'Pagne Complet'), ('Pagne Maniere', 'Pagne Maniere'), ('Patanlon', 'Patanlon'), ('Tenu Scolaire', 'Tenu Scolaire'), ('Tenu Securite', 'Tenu Securite'), ('AUTRES', 'AUTRES')], default='Boubou', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coude', models.FloatField()),
                ('epaule', models.FloatField()),
                ('manche', models.FloatField(blank=True, null=True)),
                ('tour_manche', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('poitrine', models.FloatField(blank=True, null=True)),
                ('longueur_boubou', models.FloatField(blank=True, null=True)),
                ('longueur_patanlon', models.FloatField(blank=True, null=True)),
                ('fesse', models.FloatField(blank=True, null=True)),
                ('ceinture', models.FloatField(blank=True, null=True)),
                ('cuisse', models.FloatField(blank=True, null=True)),
                ('patte', models.FloatField(blank=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='kalaliso.person', verbose_name='Nom client')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couture', models.CharField(choices=[('BRODERIE', 'Broderie'), ('COUTURE SIMPLE', 'Couture simple'), ('COUTURE A MAIN', 'Couture a main'), ('REPARATION', 'Reparation')], default='Broderie', max_length=25)),
                ('tissu', models.CharField(choices=[('BAZIN GETZNER', 'BAZIN GETZNER'), ('BAZIN RICHE', 'BAZIN RICHE'), ('BAZIN MOYEN', 'BAZIN MOYEN'), ('WAX', 'WAX'), ('TISSU', 'TISSU'), ('LEGER', 'LEGER'), ('BRODE', 'BRODE'), ('PERCALE', 'PERCALE'), ('VOILE', 'VOILE'), ('BOGOLAN', 'BOGOLAN'), ('AUTRES', 'AUTRES')], default='BAZIN GETZNER', max_length=25)),
                ('couloir', models.CharField(choices=[('BLANCHE', 'BLANCHE'), ('ROUGE SANG', 'ROUGE SANG'), ('BLEU', 'BLEU'), ('ORANGE', 'ORANGE'), ('ROSE', 'ROSE'), ('VERT', 'VERT'), ('GRIS', 'GRIS'), ('GRIS CLAIR', 'GRIS CLAIR'), ('VIOLET', 'VIOLET'), ('MARON', 'MARON'), ('MARON CLAIR', 'MARON CLAIR'), ('TURGUOISE', 'TURGUOISE'), ('JAUNE', 'JAUNE'), ('JAUNE COUSIN', 'JAUNE COUSIN'), ('NOIR', 'NOIR'), ('BAGA', 'BAGA'), ('BAGA CLAIR', 'BAGA CLAIR'), ('DEUX TONS', 'DEUX TONS'), ('MULTICOLOR', 'MULTICOLOR')], default='BLANCHE', max_length=25)),
                ('quantite', models.PositiveSmallIntegerField()),
                ('metrage', models.FloatField()),
                ('prix_unitaire', models.FloatField()),
                ('montant_total', models.FloatField()),
                ('avance', models.FloatField()),
                ('reliquat', models.FloatField()),
                ('remise', models.FloatField(default=0)),
                ('reception', models.DateTimeField(auto_now_add=True)),
                ('rendez_vous', models.DateField()),
                ('livre', models.BooleanField(default=False)),
                ('command_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalaliso.person', verbose_name='Titulaire command')),
                ('produit', models.ManyToManyField(to='kalaliso.Produit', verbose_name='Nouveau produit')),
            ],
            options={
                'ordering': ('reception',),
            },
        ),
    ]
