# Generated by Django 3.1 on 2021-06-19 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalaliso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.FloatField(blank=True, null=True)),
                ('rendez_vous', models.DateTimeField()),
                ('livre', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('command_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalaliso.person', verbose_name='Titulaire command')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemsDepense',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='command_person',
        ),
        migrations.AddField(
            model_name='produit',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ItemsOrders',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='kalaliso.Produit', verbose_name='list_commande'),
        ),
    ]
